# Generated by Django 3.1.2 on 2020-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('petrol', models.CharField(max_length=100)),
                ('travel', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('rent', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
